/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ExampleListItem } from "./components/example-list/example-list";
export { ExampleListItem } from "./components/example-list/example-list";
export namespace Components {
    interface ExampleInput {
        /**
          * Whether the input is disabled
          * @default false
         */
        "disabled": boolean;
        /**
          * Placeholder text for the input
          * @default ''
         */
        "placeholder": string;
        /**
          * The current value of the input
          * @default ''
         */
        "value": string;
    }
    interface ExampleList {
        /**
          * The list of items to display
          * @default []
         */
        "items": ExampleListItem[];
    }
}
export interface ExampleInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLExampleInputElement;
}
declare global {
    interface HTMLExampleInputElementEventMap {
        "exampleChange": string;
        "exampleFocus": void;
        "exampleBlur": void;
    }
    interface HTMLExampleInputElement extends Components.ExampleInput, HTMLStencilElement {
        addEventListener<K extends keyof HTMLExampleInputElementEventMap>(type: K, listener: (this: HTMLExampleInputElement, ev: ExampleInputCustomEvent<HTMLExampleInputElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLExampleInputElementEventMap>(type: K, listener: (this: HTMLExampleInputElement, ev: ExampleInputCustomEvent<HTMLExampleInputElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLExampleInputElement: {
        prototype: HTMLExampleInputElement;
        new (): HTMLExampleInputElement;
    };
    interface HTMLExampleListElement extends Components.ExampleList, HTMLStencilElement {
    }
    var HTMLExampleListElement: {
        prototype: HTMLExampleListElement;
        new (): HTMLExampleListElement;
    };
    interface HTMLElementTagNameMap {
        "example-input": HTMLExampleInputElement;
        "example-list": HTMLExampleListElement;
    }
}
declare namespace LocalJSX {
    interface ExampleInput {
        /**
          * Whether the input is disabled
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Emitted when the input loses focus
         */
        "onExampleBlur"?: (event: ExampleInputCustomEvent<void>) => void;
        /**
          * Emitted when the value changes
         */
        "onExampleChange"?: (event: ExampleInputCustomEvent<string>) => void;
        /**
          * Emitted when the input receives focus
         */
        "onExampleFocus"?: (event: ExampleInputCustomEvent<void>) => void;
        /**
          * Placeholder text for the input
          * @default ''
         */
        "placeholder"?: string;
        /**
          * The current value of the input
          * @default ''
         */
        "value"?: string;
    }
    interface ExampleList {
        /**
          * The list of items to display
          * @default []
         */
        "items"?: ExampleListItem[];
    }
    interface IntrinsicElements {
        "example-input": ExampleInput;
        "example-list": ExampleList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "example-input": LocalJSX.ExampleInput & JSXBase.HTMLAttributes<HTMLExampleInputElement>;
            "example-list": LocalJSX.ExampleList & JSXBase.HTMLAttributes<HTMLExampleListElement>;
        }
    }
}
